### ISSUE TITLE
【功能需求】自定义时间戳格式

### ISSUE THREAD

**Issue by Tony-zf1** [aidenlx/mx-bili-plugin#1]
作者你好，非常感谢，这个插件终于支持b站时间戳了，使用起来方便多了！

请问能否增加一个自定义时间戳格式的功能，使用场景是：

在使用列表书写视频笔记时，希望时间戳插入在光标所在行的行尾，并换行到新一行，最终效果如下。

- 笔记一[03:55](www.bilibili.com)
- 笔记二[04:20](www.bilibili.com)
- 笔记三[05:33](www.bilibili.com)

谢谢！

**Comment by aidenlx** [comment]
你最好在Media Extended的[这个issue](https://github.com/aidenlx/media-extended/issues/32)下继续提需求，另外最好录个视频，有点没完全理解
