### ISSUE TITLE
The latest obsidian(0.13.14) doesn't work and it turn into my browser

### ISSUE THREAD

**Issue by arnodjiang** [aidenlx/mx-bili-plugin#11]
As the title, if I click "Ctrl + left mouse", and I will Jump to browser

However, if I choose "Setting-Editor-Use legacy editor" and it can work well, so please fix the bug.

Thanks for your consideration

**Comment by aidenlx** [comment]
Live preview is not yet support, FR of which is tracked [here](https://github.com/aidenlx/media-extended/issues/107)
