### ISSUE TITLE
failed to load plugin mx bili plugin

### ISSUE THREAD

**Issue by bibibimartyr** [aidenlx/mx-bili-plugin#16]
![屏幕截图 2022-01-16 111219](https://user-images.githubusercontent.com/49381756/149645875-ea4eda28-25f8-47c6-9d46-088d153166b5.png)

**Comment by NJCBY** [comment]
同样遇到这种情况

**Comment by aidenlx** [comment]
你们具体环境可以说下吗，还有obsidian版本，有试过在新的文档库里安装吗？

**Comment by NJCBY** [comment]
![%(7FXMI`ZWWC@_85}L3(5J7](https://user-images.githubusercontent.com/75885138/149722328-3d2841b1-8fb8-4f9c-92e4-b40813e2b7e6.png)
![AP~}%`61E)2N(PC10Z`DZIO](https://user-images.githubusercontent.com/75885138/149722347-e2912efa-fd1a-4f2c-8f89-da8b2a460baa.png)
在新的文档库里试了下,那个哔哩哔哩的装不上去,media 那个正常装
软件版本是最新的V0.13.19

**Comment by NJCBY** [comment]
![%(7FXMI`ZWWC@_85}L3(5J7](https://user-images.githubusercontent.com/75885138/149722704-ec208813-05df-41c9-84dd-d271bb187fac.png)

**Comment by aidenlx** [comment]
我在windows 11跟Mac上都测试了没发现这个问题。。。@NJCBY 你把新的库打包成zip发上来我看看

**Comment by NJCBY** [comment]
昨天卸载重装了下之后就能装上了,哈哈,还是感谢.

**Comment by bibibimartyr** [comment]
在新的库能够安装了

**Comment by bibibimartyr** [comment]
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2022/‎1/‎14
操作系统内部版本	19043.1466
体验	Windows Feature Experience Pack 120.2212.3920.0

在新的库能安装了

**Comment by allwaysFindFood** [comment]
> 我在windows 11跟Mac上都测试了没发现这个问题。。。@NJCBY 你把新的库打包成zip发上来我看看

发现和 annotator（0.1.9）冲突，导致该问题
