### ISSUE TITLE
Error: Fail To load mx-bili-plugin

### ISSUE THREAD

**Issue by unilem** [aidenlx/mx-bili-plugin#18]
我的 Obsidian 无法加载这个插件重装也不管用
![截屏](https://user-images.githubusercontent.com/80297895/150786834-c29db570-9373-49c2-bf44-99012491b572.png)

**Comment by whuailin** [comment]
一样的问题. obsidian 插件无法加载,在哪能看到错误log排查下吗?

**Comment by allwaysFindFood** [comment]
> 

ctrl+shift+i

**Comment by allwaysFindFood** [comment]
发现和annotator（0.1.9）冲突，导致该问题

**Comment by lifesign** [comment]
> 发现和annotator（0.1.9）冲突，导致该问题

是这个问题

**Comment by aidenlx** [comment]
@Ylem-Z @whuailin 你们检查一下是不是annotator的问题，假如是的话可以到 #17 继续反馈。我暂时先关掉这个commit，假如有不是annotator的问题可以随时重开

**Comment by unilem** [comment]
![截屏 14](https://user-images.githubusercontent.com/80297895/151692108-2c0dac2e-319b-48e6-b59c-a78e0104d842.png)
没有的用处

**Comment by aidenlx** [comment]
@Ylem-Z 无法复现，可以在新的库里试着装一下吗

**Comment by aidenlx** [comment]
@Ylem-Z 你obsidian要重启一下，应该也是 #17 的问题

**Comment by aidenlx** [comment]
@Ylem-Z https://github.com/aidenlx/mx-bili-plugin/issues/17#issuecomment-1025098988
