### ISSUE TITLE
大佬!求个字幕功能行嘛?

### ISSUE THREAD

**Issue by eterlan** [aidenlx/mx-bili-plugin#3]
现在在用这个学国外的课程, 视频在软件里面看沉浸感高了很多, 也不太容易分心了, 但有时候没听懂, b站网页版里面有字幕, 软件里面没有..所以想求个字幕功能, 或者就像youtube那样弄一个直接用原生按钮的选项.
十分感谢!

**Comment by aidenlx** [comment]
我在这开了个单独的issue：https://github.com/aidenlx/media-extended/issues/76

目前来说是[支持本地字幕](https://github.com/aidenlx/media-extended/wiki/Caption-Subtitle-Support)的，你可以考虑下载下来之后放库里
