### ISSUE TITLE
bilibili分p视频不支持

### ISSUE THREAD

**Issue by lc06** [aidenlx/mx-bili-plugin#4]
你好，我在使用mx-bili插件的过程中发现，对于bilibili上的分p视频，即便更换了每一p对应的地址，也只能播放第一p的视频内容，请问可以考虑支持一下bilibili分p视频的播放吗？

**Comment by aidenlx** [comment]
已经支持了，把你插入的原文发上来一下我看看

**Comment by lc06** [comment]
当我点击` [GAMES101-现代计算机图形学入门-闫令琪 p2]`时，还是播放p1的视频，下面是我在Obsidian里写的原文：
```markdown
## Day Planner
本日计划分为 3 部分:
1. 上午
2. 下午
3. 晚上

### 上午
- [ ] [GAMES101-现代计算机图形学入门-闫令琪 p1](https://www.bilibili.com/video/BV1X7411F744?p=1)

> - 全局光照
> - 课程主题：[28:08](https://www.bilibili.com/video/BV1X7411F744?p=1#t=1688.528519)
> - 


- [ ] [GAMES101-现代计算机图形学入门-闫令琪 p2](https://www.bilibili.com/video/BV1X7411F744?p=2)
### 下午
- [ ]
### 晚上
```
补充：我刚又尝试了一下，发现本质问题是打开的视频窗口不能自动切换视频。当打开p1视频窗口之后，再点击p2的链接，打开的p1视频窗口不会自动切换加载p2视频，必须先把p1视频窗口关掉，再点击p2的链接，才能正常播放p2的视频。

**Comment by somax** [comment]
同样的问题，关闭再打开暂时解决问题。

**Comment by aidenlx** [comment]
在[v2.10.4](https://github.com/aidenlx/media-extended/releases/tag/2.10.4)修复了
