### ISSUE TITLE
bilibili 画质没有1080P

### ISSUE THREAD

**Issue by churchilldu** [aidenlx/mx-bili-plugin#5]
> 浏览器中播放视频1080P
![image](https://user-images.githubusercontent.com/62705137/132133672-0a48f49f-0b3d-484e-9500-8398215420a3.png)
> obsidian中插入的哔哩哔哩视频
![image](https://user-images.githubusercontent.com/62705137/132133675-e9b4ea29-0c29-48b9-aa28-19d79b3e1899.png)

**Comment by aidenlx** [comment]
其实目前不需要登录会员就可以360p以上高清也是b站的疏忽😂目前还没空弄分辨率选择跟码率限制，默认配置就相当于自动分辨率，网络环境差的话会自动切换到较低的

**Comment by churchilldu** [comment]
> 其实目前不需要登录会员就可以360p以上高清也是b站的疏忽😂目前还没空弄分辨率选择跟码率限制，默认配置就相当于自动分辨率，网络环境差的话会自动切换到较低的

可能是我的网络不太好，谢谢大大的模块❤️❤️

**Comment by Tinaliasd** [comment]
大大还是建议做一下选分辨率的问题，因为有些视频属实比较长，那么播放的时候分辨率就会很低。
比如我最近在b站看左程云的算法课，每个视频都是2小时起步，导致分辨率极低，无法嵌入观看

**Comment by Tinaliasd** [comment]
期待大大，加上分辨率选项功能

**Comment by aidenlx** [comment]
后面会考虑做成浏览器插件的形式，在ob里实现播放器不可控因素太多了，后面也没精力维护了

**Comment by Tinaliasd** [comment]
b站现在好像播放视频右键可以获得一个带精确时间的网址，但是会跳转到浏览器新的窗口，不是在原窗口进行跳转播放

**Comment by YuanAaron** [comment]
> 后面会考虑做成浏览器插件的形式，在ob里实现播放器不可控因素太多了，后面也没精力维护了

催更一下，大大

**Comment by HiWQ** [comment]
any update？
