### ISSUE TITLE
不支持 https://b23.tv 短连接

### ISSUE THREAD

**Issue by somax** [aidenlx/mx-bili-plugin#6]
在使移动端分享中选择复制链接，会产生类似 https://b23.tv/PCM0fx 的短连接，目前点击链接会弹出浏览器播放，而不是在 OB 里面播放。

例子如下：
- [【OB生产力系列——在OB里实现幕布的大纲笔记效果。所用插件Outliner和Zoom。Obsidian | 黑曜石教程-哔哩哔哩】](https://b23.tv/PCM0fx)

**Comment by aidenlx** [comment]
[v2.10.5](https://github.com/aidenlx/media-extended/releases/tag/2.10.5)开始支持短链接（仅桌面端支持）
